meta_product_name: "Megaleetic"
meta_title: "Megaleetic - Osez l'aventure, vous êtes guidés!"
meta_description: "Osez l'aventure, vous êtes guidés!"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
twitter_account: "@JackyCFDTBZH"   # required for Twitter Cards
